# Generated by Django 5.0 on 2026-09-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text='Original URL provided by user', max_length=2048)),
                ('normalized_url', models.URLField(help_text='Normalized/cleaned URL', max_length=2048)),
                ('final_url', models.URLField(blank=True, help_text='Final URL after redirects', max_length=2048)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if scan failed')),
                ('total_requests', models.IntegerField(default=0)),
                ('unique_domains', models.IntegerField(default=0)),
                ('first_party_domains', models.IntegerField(default=0)),
                ('third_party_domains', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0, help_text='Scan duration in milliseconds')),
                ('document_count', models.IntegerField(default=0)),
                ('stylesheet_count', models.IntegerField(default=0)),
                ('script_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('font_count', models.IntegerField(default=0)),
                ('xhr_count', models.IntegerField(default=0)),
                ('fetch_count', models.IntegerField(default=0)),
                ('media_count', models.IntegerField(default=0)),
                ('websocket_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_scan_created_958b70_idx'), models.Index(fields=['status'], name='core_scan_status_604dde_idx')],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('path', models.TextField()),
                ('method', models.CharField(default='GET', max_length=10)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('stylesheet', 'Stylesheet'), ('script', 'Script'), ('image', 'Image'), ('font', 'Font'), ('xhr', 'XHR'), ('fetch', 'Fetch'), ('media', 'Media'), ('websocket', 'WebSocket'), ('other', 'Other')], db_index=True, max_length=20)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('status_text', models.CharField(blank=True, max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('start_time', models.FloatField(help_text='Unix timestamp when request started')),
                ('duration_ms', models.IntegerField(default=0, help_text='Request duration in milliseconds')),
                ('is_redirect', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True, max_length=2048)),
                ('failed', models.BooleanField(default=False)),
                ('failure_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.scan')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['scan', 'start_time'], name='core_resour_scan_id_1b821e_idx'), models.Index(fields=['scan', 'resource_type'], name='core_resour_scan_id_662eeb_idx'), models.Index(fields=['scan', 'hostname'], name='core_resour_scan_id_abea9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('is_first_party', models.BooleanField(default=False)),
                ('request_count', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('document_count', models.IntegerField(default=0)),
                ('stylesheet_count', models.IntegerField(default=0)),
                ('script_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('font_count', models.IntegerField(default=0)),
                ('xhr_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.scan')),
            ],
            options={
                'ordering': ['-request_count'],
                'indexes': [models.Index(fields=['scan', '-request_count'], name='core_domain_scan_id_ce2e03_idx'), models.Index(fields=['scan', 'is_first_party'], name='core_domain_scan_id_812749_idx')],
                'unique_together': {('scan', 'hostname')},
            },
        ),
    ]
